version: '2'
services: 
        
        telegram:
                build: ./telegram
                privileged: true
                restart: always
                ports: 
                        - 3000
                labels:
                        io.balena.features.dbus: '1'
                        io.balena.features.kernel-modules: '1'
                volumes: 
                        - 'shared-data:/var/data'
                        - 'shared-media:/var/media'
        
        ei-processing:
                build: ./ei-processing2
                privileged: true
                restart: always
                network_mode: host
                ports: 
                        - 80
                depends_on:
                        - telegram
                labels:
                        io.balena.features.dbus: '1'
                        io.balena.features.kernel-modules: '1'
                volumes: 
                        - 'shared-data:/var/data'
                        - 'shared-media:/var/media'
                environment:
                        - UDEV=1
                devices:
                        - '/dev:/dev'      

volumes:
        shared-data:
        shared-media:
        