version: '2.1'
services: 
        
        telegram:
                build: ./telegram
                privileged: true
                restart: always
                ports: 
                        - 3000
                labels:
                        io.balena.features.dbus: '1'
                        io.balena.features.kernel-modules: '1'
                volumes: 
                        - 'shared-data:/var/data'
                        - 'shared-media:/var/media'
        
        ei-processing:
                build: ./ei-processing
                privileged: true
                restart: always
                network_mode: host
                container_name: ei-processing
                ports: 
                        - 8080
                depends_on:
                        - telegram
                labels:
                        io.balena.features.dbus: '1'
                        io.balena.features.kernel-modules: '1'
                volumes: 
                        - 'shared-data:/var/data'
                        - 'shared-media:/var/media'
                environment:
                        - UDEV=1
                devices:
                        - '/dev:/dev'
        web:
                build: ./web
                container_name: web
                privileged: true
                restart: always
                network_mode: host
                labels:
                        io.balena.features.dbus: '1'
                        io.balena.features.kernel-modules: '1'
                ports: 
                        - 80
                depends_on:
                        - ei-processing
                volumes: 
                        - 'shared-data:/var/data'
                        - 'shared-media:/var/media'
                links:
                        - ei-processing

volumes:
        shared-data:
        shared-media:
        